DROP TABLE IF EXISTS quizzes CASCADE;

CREATE TABLE quizzes (
  id INTEGER PRIMARY KEY NOT NULL,
  owner_id INTEGER REFERENCES users(id) ON DELETE CASCADE,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  is_active BOOLEAN NOT NULL DEFAULT TRUE,
  name VARCHAR(255) NOT NULL
);
