DROP TABLE IF EXISTS quizzes CASCADE;

CREATE TABLE quizzes (
  id INTEGER PRIMARY KEY NOT NULL,
  owner_id INTEGER REFERENCES users(id) ON DELETE CASCADE,
  title VARCHAR(255) NOT NULL,
  created_at DATE NOT NULL,
  is_active BOOLEAN NOT NULL DEFAULT TRUE
);
